### ISSUE TITLE
False positive ng-mocks not in JIT.

### ISSUE THREAD

**Issue by qdelettre** [ike18t/ng-mocks#1427]
Hi !

FYI i just tried to upgrade my toy app to angular v13.0.3, and it seems something is breaking ng-mock (it was working previously in v13.0.2)

[Related PR](https://github.com/qdelettre/awesome-hangman/pull/266) 

[Actions Job log](https://github.com/qdelettre/awesome-hangman/runs/4387860014?check_suite_focus=true)

**Comment by satanTime** [comment]
Hi @qdelettre 

Thanks for the info. 

I'm on vacation, I'll be back in 1 week and take a look at the issue.

**Comment by FunnyGhost** [comment]
Same here. Using it with NX, angular 13.0.3, ng-mocks 12.5.0.

**Comment by miniskurken** [comment]
Having problems upgrading it to 13.0.3 with ng-mocks 12.5.0 as well. 
However can't seem to get it working with 13.0.2 either.

**Comment by kamilchlebek** [comment]
I think the problem is here:
https://github.com/ike18t/ng-mocks/blob/d2cf130294b4e9eef5a7efdb55487bed6f6297ce/libs/ng-mocks/src/lib/common/core.reflect.directive-resolve.ts#L1-L7

`MockDirectiveResolver` was removed in angular 13 (https://github.com/angular/angular/commit/bb9ff6003c620b3cf00232189d60097395382802#diff-a276decfccb83a8fb5eae9b051127ce2e3773c9407992869061a648e7bf1d1e5)

**Comment by Lutonite** [comment]
I've also encountered the issue in a library I'm maintaining. I have a `MockBuilder` set to mock a module defined with `@NgModule` in the test file, I've done this to check the implementation of a guard that I provide, so I had to have an example module with some routes to check that the guard is actually working.

Reading the stacktrace suggests that ng-mocks is trying to use `MockNgModuleResolver` which was removed in `@angular/compiler` 13.0.3 (where `@angular/compiler/testing` got completely nuked). Downgrading only that dependency to 13.0.2 fixed the issue for me.

Loving the project so far, I hope that a solution can be found to fix this.

Stacktrace:
```
Error: RouterModule declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely,  ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.
	    at node_modules/ng-mocks/cjs/lib/common/error.missing-decorators.js:5:1
	    at exports.default (node_modules/ng-mocks/cjs/lib/common/core.reflect.body-catch.js:16:1)
	    at node_modules/ng-mocks/cjs/lib/common/core.reflect.module-resolve.js:10:142
	    at getMockModuleDef (node_modules/ng-mocks/cjs/lib/mock-module/mock-module.js:114:1)
	    at detectMockModule (node_modules/ng-mocks/cjs/lib/mock-module/mock-module.js:123:1)
	    at MockModule (node_modules/ng-mocks/cjs/lib/mock-module/mock-module.js:161:1)
	    at node_modules/ng-mocks/cjs/lib/mock-builder/promise/init-modules.js:64:1
	    at node_modules/ng-mocks/cjs/lib/mock-builder/promise/init-universe.js:69:1
	    at MockBuilderPerformance.MockBuilderPromise.build (node_modules/ng-mocks/cjs/lib/mock-builder/mock-builder.promise.js:134:1)
	    at MockBuilderPerformance.build (node_modules/ng-mocks/cjs/lib/mock-builder/mock-builder.performance.js:96:1)
```

**Comment by satanTime** [comment]
Hi all,

I'm back and going to check and fix the issue during this week.
Thank you all for the provided info.

**Comment by nicolasstevenyates** [comment]
For me the problem was solved by downgrading to 13.0.2. Thanks you for your support.

**Comment by stefan-niedermann** [comment]
This is not a solution but a *temporary* workaround.

**Comment by chathurasudarsha** [comment]
I'm having same issue.

**Comment by SEQUOiA87** [comment]
> Hi all,
> 
> I'm back and going to check and fix the issue during this week. Thank you all for the provided info.

Thanks a lot! Shipping a fix for this asap would be greatly appreciated!

**Comment by satanTime** [comment]
Hi folks,

I'm working on the fix, but due to core changes in A13 it still requires time to properly fix it in the way that it would support A5+ versions.

Btw, are there devs which don't install `@angular/forms` or `@angular/platform-browser` modules?

**Comment by patelvimal** [comment]
Thanks @satanTime  for the fix.
Lets us know if we can contribute to this in any way possible.

Can't we update the docs that which ng-mock version support which version of angular.
So that it will be easy to consumer as well and easy to maintain as well.

**Comment by krusche** [comment]
> I'm working on the fix, but due to core changes in A13 it still requires time to properly fix it in the way that it would support A5+ versions.

Can you not release a new major version and drop support for old Angular versions?

**Comment by LPCmedia** [comment]
Would it make sense to follow angular LTS ?  with 10 ending on dec 24rth .
seems that going back that far is a maintenance nightmare. 

https://angular.io/guide/releases#support-policy-and-schedule

**Comment by satanTime** [comment]
> > I'm working on the fix, but due to core changes in A13 it still requires time to properly fix it in the way that it would support A5+ versions.
> 
> Can you not release a new major version and drop support for old Angular versions?

Yes, this is what I'm checking currently. The issue is that it's not purely `A13` change, as I understand `<=13.0.2` uses the old approach from `A5` and all younger versions use the new one, so even if I release a new major version it should still support both approaches.

Anyway the solution will be found. Either with support of all A version or just A13.

**Comment by dolanmiu** [comment]
Is there a rough time frame for when this would be fixed?

**Comment by satanTime** [comment]
Hi,

the estimate is asap. 
The last weekend, I almost solved dependencies to bring the repo to latest versions.

The next weekend, I should finish that and to switch to investigation and implementation of a fix. It may take 2 more weekends, and considering the holiday, I would expect a properly working fix around mid January.

Currently, I would recommend to stay on Angular 13.0.2 and ng-mocks 12.5.0. 

Unfortunately, this task isn't something where it's easy to help. 

If anyone has time, it would be great to fix the PR with the update to the latest jest before the upcoming weekend.

**Comment by Fafnur** [comment]
@satanTime Hi. 
Can you not release a "alpha" version, which will work > A13.02. You don't need to merge this version on master, it's only hotfix for all us, who using > A13.0.2.

**Comment by satanTime** [comment]
To release an alpha candidate, I still need to bring the repo to the latest dependencies, to ensure that the candidate will work with all of them, because otherwise - Angular 13 is supported, but the latest jest version is failing, and it will be the same story.

Might you describe, why you have to stay with `>13.0.2` and cannot downgrade to `13.0.2` until the fix has been released?

Also for all people who want to help with the project - feel free to take any [good first issue](https://github.com/ike18t/ng-mocks/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22), it will help the project a lot too.

Thank you all in advance.

**Comment by markchagers** [comment]
I just downgraded a new project to 13.0.2 and the same error still occurs!

**Comment by SEQUOiA87** [comment]
> I just downgraded an angular 13.1.2 project to 13.0.2 and the same error still occurs! This is not a big problem for me currently, but I thought it would be useful to know that downgrading an existing project to angular 13.0.2 does NOT solve the issue.

That sounds weird. For us it definitely did the trick.

Please make sure that in your .lock file `@angular/compiler` is not listed in version 13.0.3 (or above) anymore.

**Comment by waratah** [comment]
even though I listed the correct version in package,  package lock was up a few versions.   I removed node_modules and reinstalled from scratch to get it right from memory.   downgrade can be fiddly.

**Comment by FrancescoBorzi** [comment]
confirmed

**Comment by markchagers** [comment]
actually I first uninstalled @angular/cli globally and re-installed as follows: npm i @angular/cli@13.0.2.
Then I created a new project, deleted package.lock file and node_modules from my existing project, and manually copied all version numbers from the new project to package.json and did an npm install. (this was my umpteenth attempt at downgrading that project).
However, although ng version now returns 13.0.2 globally (in my home dir), inside the project directory it returns 13.0.4 (go figure). Apparently it is not humanly possible to downgrade an angular project to any specific version.
Anyway, I will wait until this ngMocks issue is fixed before updating my main project from angular 12 (I was experimenting with a test project until now)

**Comment by patelvimal** [comment]
@markchagers You can absolutely downgrade an angular version to specific version. In your package.json file remove the ~ from package version then after do the clean install( remove package-lock.json file also). Then after it will install the exact version.

//Incorrect
` "@angular/core": "~13.0.2"`

//Correct
` "@angular/core": "13.0.2"`

**Comment by LPCmedia** [comment]
its annoying to be the one to ask, but any updates regarding a fix for angular > 13.0.2 ?

**Comment by satanTime** [comment]
Hi @LPCmedia,

It's in progress. And it annoys me too. Unfortunately, Angular team did a very big change. And it needs time for a proper fix here.

**Comment by DaSchTour** [comment]
@satanTime maybe you could create an issue in angular repo we all can upvote to raise attention to this mess the angular team created with a somehow breaking change in a minor version.

**Comment by LPCmedia** [comment]
https://github.com/angular/angular/issues/44629

**Comment by cedbesafilm** [comment]
> @satanTime maybe you could create an issue in angular repo we all can upvote to raise attention to this mess the angular team created with a somehow breaking change in a minor version.

I hope the Angular team finds a solution to the problem.

But by reading the commit message the say

```
This commit also empties `@angular/compiler/testing` as it is no longer
necessary (this is safe since compiler packages are not public API). It can
be deleted in the future.
```

Not being a public API I think they don't care to keep it and therefore I think (even if I don't hope so) that we will need to find a solution that is not based exclusively on Angular internal API (if possible)

**Comment by LPCmedia** [comment]
Seems like a fair response from @JoostK on the related [angular issue](https://github.com/angular/angular/issues/44629) . Probably trying to support both view engine and Ivy doesn't make a lot of sense and would be a lot of effort. 

seems that they are available for questions + comments as well.

**Comment by satanTime** [comment]
Hi all,

wish you all a happy new year!

A good news. [`v13.0.0-alpha.1`](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.1) is here, might you test and post your feedback here?
For now, it works with `>13.0.2` only. However, it's possible to support all view engines without huge pain.
I'll be working on that tomorrow and upcoming weekends.

**Comment by patelvimal** [comment]
> 

Hi @satanTime thanks for this, you are doing wonderful work for the community. Let me know if any help is needed. Happy to contribute.

**Comment by satanTime** [comment]
Hi @patelvimal, please find me on telegram, my username there is `satanTime`.

**Comment by DaSchTour** [comment]
> Hi all,
> 
> wish you all a happy new year!
> 
> A good news. [`v13.0.0-alpha.1`](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.1) is here, might you test and post your feedback here? For now, it works with `>13.0.2` only. However, it's possible to support all view engines without huge pain. I'll be working on that tomorrow and upcoming weekends.

I just tested 13.0.0-alpha.1 and most tests work fine. But I get errors when mocking third party libraries for example Angular Components/Material.

So `MockModule(MatFormFieldModule)` fails with `MatFormFieldControl declaration has been passed into ng-mocks without Angular decorators.`

I'm also getting similar errors for `MatDialog` which I have mockes using `@ngneat/spectator` `mockProvider`.

**Comment by satanTime** [comment]
Hi @DaSchTour,

thanks for the feedback. Might you share the version of `angular-material`?

Regarding `@ngneat/spectator` and `mockProvider`, as far as I know they don't use `ng-mocks`, it would be better to create an issue in their project.

**Comment by DaSchTour** [comment]
@satanTime it's @angular/material 13.1.1

The thing is, that the error message is the same as when using ng-mocks and the link also points to this repo. But I'll also create an issue there, maybe they can utilize some of your work.

**Comment by satanTime** [comment]
@DaSchTour, aha, if the error is the same - then my bad, looks like they added `ng-mocks` at some point. However, I haven't checked it, just a guess :) 

Good, I'm checking 13.1.1 and a fix for it will be in the next alpha, hopefully today.

**Comment by DaSchTour** [comment]
@satanTime sometimes by using `mockProvider(MatDialog)`and sometimes by using the mocks property `mocks: [MatDialog],`. But I also just saw, that I have `ngMocks.autoSpy('jest');`configured. I'm not sure if that is even a good idea to have both. I'll just check what happens if I disable `autoSpy`.

**Comment by satanTime** [comment]
Hm... this is odd... I'll try it locally.

**Comment by DaSchTour** [comment]
> Hm... this is odd... I'll try it locally.

If you use `MockModule` in `defineGlobalsInjections()` from `@ngneat/spectator` this issue occurs.

**Comment by satanTime** [comment]
@DaSchTour, Aha, now it makes sense. Might you update in node_modules that `@ngneat/spectator` would also use alpha version on `ng-mocks`?

**Comment by satanTime** [comment]
Hi all,

[13.0.0-alpha.2](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.2) has been published.
It should properly support `angular-material`.

It's still requires `>13.0.2`.

**Comment by jnk22** [comment]
I have had the same errors as reported by @DaSchTour earlier.

With Angular 13.1.1, Angular Material 13.1.1 and your newest update [13.0.0-alpha.2](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.2), all errors are gone 🙌 

Thank you!

**Comment by DaSchTour** [comment]
> I have had the same errors as reported by @DaSchTour earlier.
> 
> With Angular 13.1.1, Angular Material 13.1.1 and your newest update [13.0.0-alpha.2](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.2), all errors are gone 🙌
> 
> Thank you!

Can confirm. Thanks for the great work!

**Comment by satanTime** [comment]
Nice. Thanks for good news!!!

**Comment by kekel87** [comment]
Hello,

I confirm, all my tests works without any errors with [13.0.0-alpha.2](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.2) version !! 👍 

My versions:
- Angular CLI 13.1.2
- Angular 13.1.1
- Angular Material 13.1.1
- NGRX 13.0.2

Thanks again for the time you spent there!

**Comment by icorne** [comment]
Works for us as well!

**Comment by martinrogne** [comment]
Can confirm 13.0.0-alpha.2 working on the nx / angular projects I have upgraded so far with Angular 13.1.1 and Jest.

**Comment by SnakeSVx** [comment]
Seems to work for most testcases for us, but not all yet.

Pipes are not getting mocked that are available inside a module using MockModule(....)
And we have 3 custom material form field components that still give the error. (All other types of components seems to be properly mocked)

All 3 components are like the following: 

```
@Component({
  selector: 'our-custom-selector',
  templateUrl: './custom-form.html',
  styleUrls: ['./custom-form.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: MatFormFieldControl,
      useExisting: CustomFormComponent
    }
  ]
})
export class CustomFormComponent implements OnInit, AfterViewInit,
  ControlValueAccessor, MatFormFieldControl<Number>>, OnDestroy, AfterContentChecked {
  
  ...
  
 }
```

**Comment by satanTime** [comment]
Hi @SnakeSVx,

Thanks for the info. Might you share how the pipe's definition and decoration look like, how it's imported in its module and how its test fails?

Thank you in advance.

**Comment by SnakeSVx** [comment]
Example pipe: 

```
import { DatePipe } from '@angular/common';
import { Inject, Injectable, LOCALE_ID, Pipe, PipeTransform } from '@angular/core';

@Injectable()
@Pipe({
  name: 'tijdstip'
})
export class TijdstipPipe extends DatePipe implements PipeTransform {

  constructor(@Inject(LOCALE_ID) locale: string) {
    super(locale);
  }

  transform(value: null | undefined): null;
  transform(value: null | undefined, inclusiefSeconden: boolean): null;
  transform(value: Date | string | number | undefined): string | null;
  transform(value: Date | string | number | undefined, inclusiefSeconden: boolean): string | null;
  transform(value: Date | string | number | null | undefined): string | null
  transform(value: Date | string | number | null | undefined, inclusiefSeconden?: boolean): string | null {
    return super.transform(
      value,
      inclusiefSeconden ? 'dd/MM/yyyy HH:mm:ss' :'dd/MM/yyyy HH:mm',
      undefined,
      'nl-BE'
    );
  }

}
```

Example module:

```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { TijdstipPipe } from './tijdstip.pipe';
import { TimeagoCustomFormatter, TimeagoFormatter, TimeagoIntl, TimeagoModule } from 'ngx-timeago';

@NgModule({
  declarations: [
      TijdstipPipe,
      ....
      ],
     imports: [
       CommonModule,
       TimeagoModule.forChild({
       intl: {provide: TimeagoIntl, useClass: TimeAgoTranslation},
       formatter: { provide: TimeagoFormatter, useClass: TimeagoCustomFormatter }
     })],
     exports: [
         TijdstipPipe,
         ....,
         TimeagoModule
     ]
})
export class CorePipesModule {}
```

Testcase:

Fails with

`Error: NG0302: The pipe 'tijdstip' could not be found in the 'AuditInfoComponent' component!. Find more at https://angular.io/errors/NG0302`

when running a part in the test where it should trigger the Pipe.

The html for the component contains this: `<span>{{info.date | tijdstip:true}}</span>`

```
import { createComponentFactory, Spectator } from '@ngneat/spectator/jest';
import { CorePipesModule } from '@nx-workspace/pipes';
import 'html-validate/jest';
...
import { MockComponent, MockModule } from 'ng-mocks';

describe('AuditInfoComponent', () => {
  let component: AuditInfoComponent;
  let spectator: Spectator<AuditInfoComponent>

  const createComponent = createComponentFactory({
    component: AuditInfoComponent,
    imports: [
      MockModule(CorePipesModule)
    ]
  });

  beforeEach(() => {
    spectator = createComponent();
    component = spectator.component;
  });
  
   it('should create', () => {
    expect(component).toBeTruthy();
  });
  
  it('should contain valid html without user', () => {
      expect(spectator.element).toHTMLValidate();
    });
   ....
   
```

**Comment by SnakeSVx** [comment]
And before I forgot, versions of all the libraries: 

- Angular + material: 13.1.1 (cli and build-angular are 13.1.2)
- Nx: 13.4.4
- Jest: 27.2.3
- @ngneat/spectator: 10.0.0 (also tested with 9.0.0)
-

**Comment by LPCmedia** [comment]
working good for us so far. I did see an exception where we have an animation complete callback. Ill post shortly.

**Comment by krusche** [comment]
looking good for us 👍

**Comment by daniel-sc** [comment]
When switching from v12.5.1 to 13.0.0-alpha.2 (other setup unchanged: Angular 13.0.2, jasmine 3.10.1) I get the following two errors for some tests:

**Unexpected synthetic listener** 

This occurs when mocking a component that has animations defined. `NoopAnimationsModule` is imported into the testing module.

```
Error: Unexpected synthetic listener @showDismiss.done found. Please make sure that:
	  - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
	  - There is corresponding configuration for the animation named `@showDismiss.done` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
	Error: Unexpected synthetic listener @showDismiss.done found. Please make sure that:
	  - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
	  - There is corresponding configuration for the animation named `@showDismiss.done` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
	    at checkNoSyntheticProp (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2020/platform-browser.mjs:742:15)
	    at DefaultDomRenderer2.listen (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2020/platform-browser.mjs:732:24)
	    at BaseAnimationRenderer.listen (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2020/animations.mjs:299:30)
	    at listenerInternal (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:15245:44)
	    at ɵɵsyntheticHostListener (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:15155:5)
	    at Object.hostBindings (ng:///MockOfSbbNotification.js:18:21)
	    at invokeHostBindingsInCreationMode (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:10358:13)
	    at invokeDirectivesHostBindings (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:10341:17)
	    at createDirectivesInstances (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:9668:9)
	    at ɵɵelementStart (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:14864:9)
	Error: Expected undefined to be truthy.
	    at <Jasmine>
	    at UserContext.<anonymous> (http://127.0.0.1:9876/_karma_webpack_/webpack:/src/app/order/assignment/assignment-validation-notification/assignment-validation-notification.component.spec.ts:27:23)
	    at ZoneDelegate.invoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
	    at ProxyZoneSpec.onInvoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
```



**passed into ng-mocks without Angular decorators**

This happens in two different tests:

1. Mocking the erronous component with `MockComponets(..)` and the component is annotated as a `@Component(..)` but inherits from a `@Directive()`.
2. The erronous component is _not_ mocked, but declared directly in `declarations` of the testing module - maybe it is because it is overwritten? (`.overrideComponent(WeightInputComponent , NG_CONTROL_TEST_PROVIDER)`)

```
Failed: WeightInputComponent declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely,  ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.
	Error: WeightInputComponent declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely,  ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.
	    at http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/cjs/lib/common/error.missing-decorators.js:5:1
	    at push.67197.exports.default (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/cjs/lib/common/core.reflect.body-catch.js:16:1)
	    at http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/cjs/lib/common/core.reflect.directive-resolve.js:18:6
	    at decorateClass (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/cjs/lib/mock-component/mock-component.js:276:1)
	    at MockComponent (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/cjs/lib/mock-component/mock-component.js:310:1)
	    at Array.map (<anonymous>)
	    at MockComponents (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/cjs/lib/mock-component/mock-component.js:286:1)
	    at UserContext.<anonymous> (http://127.0.0.1:9876/_karma_webpack_/webpack:/src/app/order/assignment/assignment-pos/assingment-pos-row-editor/assignment-pos-row-editor.component.spec.ts:43:23)
	    at ZoneDelegate.invoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
	    at AsyncTestZoneSpec.onInvoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1196:1)
	NullInjectorError: R3InjectorError(DynamicTestModule)[WaggonNumberPipe -> WaggonNumberPipe]: 
	  NullInjectorError: No provider for WaggonNumberPipe!
	error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'WaggonNumberPipe', 'WaggonNumberPipe' ] })
	NullInjectorError: R3InjectorError(DynamicTestModule)[WaggonNumberPipe -> WaggonNumberPipe]: 
	  NullInjectorError: No provider for WaggonNumberPipe!
	    at NullInjector.get (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11139:27)
	    at R3Injector.get (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11306:33)
	    at R3Injector.get (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11306:33)
	    at NgModuleRef.get (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:22189:33)
	    at Object.get (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:21862:35)
	    at lookupTokenUsingModuleInjector (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:3349:39)
	    at getOrCreateInjectable (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:3461:12)
	    at ɵɵdirectiveInject (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:14720:12)
	    at NodeInjectorFactory.factory (ng:///AssignmentPosRowEditorComponent/ɵfac.js:4:59)
	    at getNodeInjectable (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:3556:44)
	TypeError: Cannot set properties of undefined (setting 'assignmentPos')
	    at UserContext.<anonymous> (http://127.0.0.1:9876/_karma_webpack_/webpack:/src/app/order/assignment/assignment-pos/assingment-pos-row-editor/assignment-pos-row-editor.component.spec.ts:153:30)
	    at ZoneDelegate.invoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
	    at ProxyZoneSpec.onInvoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
	    at ZoneDelegate.invoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
	    at Zone.run (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)
	    at runInTestZone (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:567:1)
	    at UserContext.<anonymous> (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:582:1)
	    at <Jasmine>
	TypeError: Cannot read properties of undefined (reading 'destroy')
	    at UserContext.<anonymous> (http://127.0.0.1:9876/_karma_webpack_/webpack:/src/app/order/assignment/assignment-pos/assingment-pos-row-editor/assignment-pos-row-editor.component.spec.ts:79:13)
	    at ZoneDelegate.invoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
	    at ProxyZoneSpec.onInvoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
	    at ZoneDelegate.invoke (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
	    at Zone.run (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)
	    at runInTestZone (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:567:1)
	    at UserContext.<anonymous> (http://127.0.0.1:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:582:1)
	    at <Jasmine>

```

**Comment by bboydflo** [comment]
also good here. although first time I run the tests, feels much slower than before. my guess is that's probably jest or jest-preset-angular. just wanted to mention it

thanks for all the effort!

**Comment by satanTime** [comment]
Hi all, [13.0.0-alpha.3](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.3) has been released. It supports all angular versions.

Now I need to polish and restore all CI checks, and after that I'll check animations and FooBarDirective issue (hopefully it has been fixed by alpha.3 already), and then, I'll release a stable version.

Thank you all for your support and help.

**Comment by satanTime** [comment]
Hi @bboydflo, regarding slower tests, I need a fix in jest: https://github.com/facebook/jest/issues/11483.
Unfortunately, maintainers have been ignoring it for a quite long time and there is not much I can do currently.

**Comment by satanTime** [comment]
Hi all, [13.0.0-alpha.4](https://www.npmjs.com/package/ng-mocks/v/13.0.0-alpha.4) has been released.

**Comment by SnakeSVx** [comment]
Apart from the pipes issue (https://github.com/ike18t/ng-mocks/issues/1587). All our tests are green now as well :)

So far we can continue without mocking the pipes.

**Comment by satanTime** [comment]
Hi @SnakeSVx, thanks for the info.

Pipes should be fixed by [v13.0.0-alpha.5](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.0-alpha.5). It was a good catch, thank you a lot!

Regarding id - could you provide a bit more context here? Is it on all components or only on some of them? If it's on some - could you share their declaration? if it's on all - could you share how your tests look like that they have id="undefined"?

Thank you in advance!

**Comment by SnakeSVx** [comment]
@satanTime pipes seems to be fixed :)

Regarding the ID, it's the same components as before again. I'm guessing it's the hostbinding in them that's causing it.

```
@Component({
  selector: 'our-custom-selector',
  templateUrl: './custom-form.html',
  styleUrls: ['./custom-form.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: MatFormFieldControl,
      useExisting: CustomFormComponent
    }
  ]
})
export class CustomFormComponent implements OnInit, AfterViewInit,
  ControlValueAccessor, MatFormFieldControl<Number>>, OnDestroy, AfterContentChecked {
  
  static nextId = 0;
  
  @HostBinding()
  id = `custom-form-${++CustomFormComponent.nextId}`;
  
  ...
  
 }
```

If I disable that HostBinding the test succeeds.

**Comment by satanTime** [comment]
Hi @SnakeSVx,

Yes. I've added host bindings and host listeners. 

Now I need to think whether we need them in mocked declarations. And, knowing that nobody has complained about them for years - looks like it was a mistake :)

**Comment by SEQUOiA87** [comment]
FYI: It seems we were also affected by the problem with mocking pipes, now with alpha.5 it's fixed. 

Thanks a lot for your work!

**Comment by MattBrou** [comment]
You're a life saver @satanTime. Thanks for you great work.

**Comment by satanTime** [comment]
[v13.0.0-alpha.6](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.0-alpha.6) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by satanTime** [comment]
Hi @SnakeSVx, please check the latest release. Hopefully, it brings all your tests to the green state again.

The next step is to verify issue with animations: https://github.com/ike18t/ng-mocks/issues/1586 and then to release a stable version.
if anyone is facing any issues - feel free to drop a line here.

Thank you all.

**Comment by SnakeSVx** [comment]
Same, all green for me now as well. 

Thank you for all the help and providing us with this great library :)

**Comment by satanTime** [comment]
Awesome! Thank you all for help and feedback. 

Stay in touch 🤙🏼

**Comment by cdupetit** [comment]
Hello @satanTime,
I get this warning with a mat-checkbox component when I run my jest test.
```
  console.error
    NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div'.

      at logUnknownPropertyError (node_modules/@angular/core/fesm2015/core.mjs:10119:13)
      at elementPropertyInternal (node_modules/@angular/core/fesm2015/core.mjs:10031:13)
      at ɵɵproperty (node_modules/@angular/core/fesm2015/core.mjs:14431:9)
      at MockOfMatCheckbox_Template (ng:/MockOfMatCheckbox.js:65:9)
      at executeTemplate (node_modules/@angular/core/fesm2015/core.mjs:9593:9)
      at refreshView (node_modules/@angular/core/fesm2015/core.mjs:9459:13)
      at refreshComponent (node_modules/@angular/core/fesm2015/core.mjs:10
```
Best Regards

**Comment by satanTime** [comment]
Hi @cdupetit,

Could you try .6?

**Comment by cdupetit** [comment]
> Hi @cdupetit,
> 
> Could you try .6?

This version fix the warning.
Thanks !

**Comment by maxs-rose** [comment]
.6 is working for us with Angular 13 and Kendo UI

**Comment by satanTime** [comment]
[v13.0.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by squelix** [comment]
Everything is working fine now !! :) Thanks !!!!

**Comment by Rlcolli4** [comment]
I just set this up on our unit tests and things are working great. Thank you so much for your hard work!
